# Generated by Django 4.2 on 2023-06-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'managed': False},
        ),
    ]
