# Generated by Django 4.2 on 2023-06-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_packages_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages',
            table='PACKAGES',
        ),
    ]
